[package]
name = "hashsign"
version = "0.1.0"
authors = ["quininer kel <quininer@live.com>"]

[dependencies]
serde = "0.7"
serde_macros = "0.7"
bincode = { version = "0.5", features = [ "serde" ] }
rust-crypto = "0.2"
rand = "0.3"
